api_platform:
    title: Hanooti API
    version: 0.1.0
    mapping:
        paths:
            - '%kernel.project_dir%/src/ApiResource'
            - '%kernel.project_dir%/src/Entity'
    defaults:
        stateless: true
        pagination_client_enabled: true
        pagination_client_items_per_page: true
        pagination_items_per_page: 20
        pagination_maximum_items_per_page: 100
    formats:
        jsonld: ['application/ld+json']
        json: ['application/json']
        xml: ['application/xml', 'text/xml']
