import { library, type IconProp } from '@fortawesome/fontawesome-svg-core';
import {
  faArrowRight,
  faArrowRightToBracket,
  faBars,
  faBagShopping,
  faCashRegister,
  faChartLine,
  faCircleCheck,
  faEnvelope,
  faGift,
  faHeadphonesSimple,
  faImage,
  faMagnifyingGlass,
  faLock,
  faPalette,
  faPenToSquare,
  faLightbulb,
  faPlus,
  faRightFromBracket,
  faShieldHalved,
  faShop,
  faStar,
  faStore,
  faTags,
  faUtensils,
  faTrashCan,
  faTruck,
  faUsers,
  faWarehouse,
  faEye,
  faEyeSlash,
} from '@fortawesome/free-solid-svg-icons';
import { faFacebook, faGoogle, faInstagram, faLinkedin, faMicrosoft, faTiktok, faWhatsapp, faXTwitter, faYoutube } from '@fortawesome/free-brands-svg-icons';

library.add(
  faArrowRight,
  faArrowRightToBracket,
  faBars,
  faBagShopping,
  faCashRegister,
  faChartLine,
  faCircleCheck,
  faFacebook,
  faGoogle,
  faEnvelope,
  faGift,
  faHeadphonesSimple,
  faImage,
  faMagnifyingGlass,
  faInstagram,
  faLinkedin,
  faLightbulb,
  faMicrosoft,
  faLock,
  faPalette,
  faPenToSquare,
  faPlus,
  faRightFromBracket,
  faShieldHalved,
  faShop,
  faStar,
  faStore,
  faTags,
  faUtensils,
  faTrashCan,
  faTruck,
  faUsers,
  faWarehouse,
  faEye,
  faEyeSlash,
  faXTwitter,
  faTiktok,
  faWhatsapp,
  faYoutube,
);

export const appIcons = {
  login: 'arrow-right-to-bracket',
  arrowRight: 'arrow-right',
  bars: 'bars',
  logout: 'right-from-bracket',
  shop: 'shop',
  store: 'store',
  pos: 'cash-register',
  products: 'bag-shopping',
  stock: 'warehouse',
  promotions: 'tags',
  loyalty: 'gift',
  sponsors: 'star',
  users: 'users',
  dashboard: 'chart-line',
  theme: 'palette',
  security: 'shield-halved',
  mail: 'envelope',
  lock: 'lock',
  instagram: 'instagram',
  linkedin: 'linkedin',
  x: 'x-twitter',
  truck: 'truck',
  edit: 'pen-to-square',
  trash: 'trash-can',
  plus: 'plus',
  image: 'image',
  search: 'magnifying-glass',
  eye: 'eye',
  eyeSlash: 'eye-slash',
  check: 'circle-check',
  headphones: 'headphones-simple',
  lightbulb: 'lightbulb',
  utensils: 'utensils',
  facebook: 'facebook',
  google: ['fab', 'google'] as IconProp,
  microsoft: ['fab', 'microsoft'] as IconProp,
} as const;
