<?php

namespace App\State\Routing;

use ApiPlatform\Metadata\Operation;
use ApiPlatform\State\ProviderInterface;
use App\ApiResource\Routing\RoutesResource;

/** @implements ProviderInterface<RoutesResource> */
final class RoutesProvider implements ProviderInterface
{
    public function provide(Operation $operation, array $uriVariables = [], array $context = []): RoutesResource
    {
        unset($operation, $uriVariables, $context);

        return new RoutesResource(
            publicRoutes: [
                [
                    'slug' => 'home',
                    'title' => 'Hanooti | La Marketplace B2B pour les Indépendants',
                    'path' => '/',
                    'section' => 'Public',
                    'description' => 'La Marketplace B2B pour les indépendants.',
                    'icon' => 'shop',
                    'access' => 'public',
                ],
                [
                    'slug' => 'boutiques',
                    'title' => 'Toutes les boutiques',
                    'path' => '/boutiques',
                    'section' => 'Public',
                    'description' => 'Marketplace publique pour découvrir les boutiques locales.',
                    'icon' => 'store',
                    'access' => 'public',
                ],
                [
                    'slug' => 'boutique-storefront',
                    'title' => 'Boutique - Vitrine personnalisée',
                    'path' => '/boutiques/luxe-paris',
                    'section' => 'Public',
                    'description' => 'Vitrine boutique immersive avec produits, offre et navigation.',
                    'icon' => 'store',
                    'access' => 'public',
                ],
                [
                    'slug' => 'product-detail',
                    'title' => 'Fiche produit',
                    'path' => '/boutiques/luxe-paris/products/robe-de-soiree',
                    'section' => 'Public',
                    'description' => 'Fiche produit détaillée avec variantes, stock et appel à l’action.',
                    'icon' => 'products',
                    'access' => 'public',
                ],
                [
                    'slug' => 'cart',
                    'title' => 'Panier',
                    'path' => '/cart',
                    'section' => 'Public',
                    'description' => 'Panier client avec récapitulatif, quantités et passage au checkout.',
                    'icon' => 'pos',
                    'access' => 'public',
                ],
                [
                    'slug' => 'checkout',
                    'title' => 'Paiement sécurisé',
                    'path' => '/checkout',
                    'section' => 'Public',
                    'description' => 'Checkout sécurisé avec livraison et paiement.',
                    'icon' => 'security',
                    'access' => 'public',
                ],
                [
                    'slug' => 'quote',
                    'title' => 'Système de devis',
                    'path' => '/quote',
                    'section' => 'Public',
                    'description' => 'Demande de devis multi-étapes pour les clients.',
                    'icon' => 'tags',
                    'access' => 'public',
                ],
                [
                    'slug' => 'confirmation',
                    'title' => 'Confirmation de commande',
                    'path' => '/order-confirmation',
                    'section' => 'Public',
                    'description' => 'Page de succès post-paiement avec suivi commande.',
                    'icon' => 'security',
                    'access' => 'public',
                ],
            ],
            adminRoutes: [
                [
                    'slug' => 'dashboard',
                    'title' => 'Dashboard Back-office',
                    'path' => '/admin',
                    'section' => 'Admin',
                    'description' => 'Vue générale du SaaS multi-boutique.',
                    'icon' => 'dashboard',
                    'access' => 'admin',
                ],
                [
                    'slug' => 'dashboard',
                    'title' => 'Dashboard Back-office',
                    'path' => '/admin/dashboard',
                    'section' => 'Admin',
                    'description' => 'Vue générale du SaaS multi-boutique.',
                    'icon' => 'dashboard',
                    'access' => 'admin',
                ],
                [
                    'slug' => 'super-admin-dashboard',
                    'title' => 'Tableau de bord Super Admin',
                    'path' => '/admin/super-admin-dashboard',
                    'section' => 'Admin',
                    'description' => 'Pilotage plateforme, revenus, boutiques et santé du SaaS.',
                    'icon' => 'security',
                    'access' => 'admin',
                ],
                [
                    'slug' => 'boutique-dashboard',
                    'title' => 'Boutique Management Dashboard',
                    'path' => '/admin/boutique-dashboard',
                    'section' => 'Boutique',
                    'description' => 'KPI opérationnels, commandes récentes et performance boutique.',
                    'icon' => 'dashboard',
                    'access' => 'admin',
                ],
                [
                    'slug' => 'boutiques',
                    'title' => 'Gestion des Boutiques',
                    'path' => '/admin/boutiques',
                    'section' => 'Boutique',
                    'description' => 'Créer, activer et administrer les boutiques de la plateforme.',
                    'icon' => 'store',
                    'access' => 'admin',
                ],
                [
                    'slug' => 'boutique-admins',
                    'title' => 'Admins boutique',
                    'path' => '/admin/boutique-admins',
                    'section' => 'Admin',
                    'description' => 'Consultation des administrateurs rattachés aux boutiques.',
                    'icon' => 'users',
                    'access' => 'admin',
                ],
                [
                    'slug' => 'settings',
                    'title' => 'Paramètres boutique',
                    'path' => '/admin/settings',
                    'section' => 'Boutique',
                    'description' => 'Logo, domaine, réseaux sociaux et options boutique.',
                    'icon' => 'theme',
                    'access' => 'admin',
                ],
                [
                    'slug' => 'appearance',
                    'title' => 'Boutique en ligne',
                    'path' => '/admin/appearance',
                    'section' => 'Boutique',
                    'description' => 'Thème, couleurs et apparence du storefront.',
                    'icon' => 'theme',
                    'access' => 'admin',
                ],
                [
                    'slug' => 'theme',
                    'title' => 'Personnalisation du Front-office',
                    'path' => '/admin/theme',
                    'section' => 'Boutique',
                    'description' => 'Couleurs, navigation, pages et catégories mises en avant.',
                    'icon' => 'theme',
                    'access' => 'admin',
                ],
                [
                    'slug' => 'users',
                    'title' => 'Utilisateurs boutique',
                    'path' => '/admin/users',
                    'section' => 'Admin',
                    'description' => 'Admins boutique, caissiers et droits opérationnels.',
                    'icon' => 'users',
                    'access' => 'admin',
                ],
                [
                    'slug' => 'customers',
                    'title' => 'Clients',
                    'path' => '/admin/customers',
                    'section' => 'Commerce',
                    'description' => 'Comptes clients, historique d\'achat et segments.',
                    'icon' => 'users',
                    'access' => 'admin',
                ],
                [
                    'slug' => 'categories',
                    'title' => 'Catégories',
                    'path' => '/admin/categories',
                    'section' => 'Commerce',
                    'description' => 'Organisation du catalogue par catégories boutique.',
                    'icon' => 'promotions',
                    'access' => 'admin',
                ],
                [
                    'slug' => 'products',
                    'title' => 'Produits',
                    'path' => '/admin/products',
                    'section' => 'Commerce',
                    'description' => 'Catalogue produits, prix, images et visibilité.',
                    'icon' => 'products',
                    'access' => 'admin',
                ],
                [
                    'slug' => 'filters',
                    'title' => 'Filtres produits',
                    'path' => '/admin/filters',
                    'section' => 'Commerce',
                    'description' => 'Attributs et filtres utilisés dans le catalogue boutique.',
                    'icon' => 'products',
                    'access' => 'admin',
                ],
                [
                    'slug' => 'product-inventory',
                    'title' => 'Product Inventory',
                    'path' => '/admin/product-inventory',
                    'section' => 'Stock',
                    'description' => 'Inventaire, stock critique, mouvements et alertes.',
                    'icon' => 'stock',
                    'access' => 'admin',
                ],
                [
                    'slug' => 'stock-movements',
                    'title' => 'Mouvements de stock',
                    'path' => '/admin/stock-movements',
                    'section' => 'Stock',
                    'description' => 'Entrées, sorties, corrections et traçabilité stock.',
                    'icon' => 'stock',
                    'access' => 'admin',
                ],
                [
                    'slug' => 'orders',
                    'title' => 'Orders & Fulfillment',
                    'path' => '/admin/orders',
                    'section' => 'Order',
                    'description' => 'Commandes web, préparation, paiement et livraison.',
                    'icon' => 'pos',
                    'access' => 'admin',
                ],
                [
                    'slug' => 'order-detail',
                    'title' => 'Détail de Commande',
                    'path' => '/admin/orders/ord-7829',
                    'section' => 'Order',
                    'description' => 'Vue détaillée d’une commande avec tracking et timeline.',
                    'icon' => 'pos',
                    'access' => 'admin',
                ],
                [
                    'slug' => 'pos',
                    'title' => 'Caisse POS',
                    'path' => '/admin/pos',
                    'section' => 'Order',
                    'description' => 'Vente comptoir, panier rapide et encaissement local.',
                    'icon' => 'pos',
                    'access' => 'admin',
                ],
                [
                    'slug' => 'promotions',
                    'title' => 'Marketing & Promotions',
                    'path' => '/admin/promotions',
                    'section' => 'Marketing',
                    'description' => 'Promotions globales, catégories, produits et priorité métier.',
                    'icon' => 'promotions',
                    'access' => 'admin',
                ],
                [
                    'slug' => 'cms',
                    'title' => 'CMS',
                    'path' => '/admin/cms',
                    'section' => 'Contenu',
                    'description' => 'Pages, blocs de contenu et publication front-office.',
                    'icon' => 'theme',
                    'access' => 'admin',
                ],
                [
                    'slug' => 'loyalty',
                    'title' => 'Fidélité',
                    'path' => '/admin/loyalty',
                    'section' => 'Loyalty',
                    'description' => 'Comptes fidélité, points et transactions client.',
                    'icon' => 'loyalty',
                    'access' => 'admin',
                ],
                [
                    'slug' => 'sponsors',
                    'title' => 'Sponsors',
                    'path' => '/admin/sponsors',
                    'section' => 'Sponsor',
                    'description' => 'Sponsors plateforme et associations par boutique.',
                    'icon' => 'sponsors',
                    'access' => 'admin',
                ],
                [
                    'slug' => 'chat',
                    'title' => 'Messagerie',
                    'path' => '/admin/chat',
                    'section' => 'Chat',
                    'description' => 'Messagerie temps réel avec les clients.',
                    'icon' => 'users',
                    'access' => 'admin',
                ],
                [
                    'slug' => 'chatbot-config',
                    'title' => 'Configuration du Chatbot',
                    'path' => '/admin/chatbot-config',
                    'section' => 'Chatbot',
                    'description' => 'Scénarios, réponses, ton et règles de l\'assistant boutique.',
                    'icon' => 'users',
                    'access' => 'admin',
                ],
                [
                    'slug' => 'subscriptions',
                    'title' => 'Gestion des abonnements',
                    'path' => '/admin/subscriptions',
                    'section' => 'Abonnements',
                    'description' => 'Plans gratuits et payants, délais, prix en DT, activation et désactivation.',
                    'icon' => 'security',
                    'access' => 'admin',
                ],
                [
                    'slug' => 'employees',
                    'title' => 'Employés',
                    'path' => '/admin/employees',
                    'section' => 'Admin',
                    'description' => 'Gestion des employés et accès opérationnels.',
                    'icon' => 'users',
                    'access' => 'admin',
                ],
                [
                    'slug' => 'delivery-companies',
                    'title' => 'Transporteurs',
                    'path' => '/admin/delivery-companies',
                    'section' => 'Delivery',
                    'description' => 'Sociétés de livraison, endpoints API et configuration transporteurs.',
                    'icon' => 'truck',
                    'access' => 'admin',
                ],
                [
                    'slug' => 'delivery-accounts',
                    'title' => 'Comptes livraison',
                    'path' => '/admin/delivery-accounts',
                    'section' => 'Delivery',
                    'description' => 'Identifiants cryptés des comptes transporteurs par boutique.',
                    'icon' => 'truck',
                    'access' => 'admin',
                ],
                [
                    'slug' => 'reviews',
                    'title' => 'Avis clients',
                    'path' => '/admin/reviews',
                    'section' => 'Commerce',
                    'description' => 'Modération et consultation des avis clients.',
                    'icon' => 'users',
                    'access' => 'admin',
                ],
                [
                    'slug' => 'delivery',
                    'title' => 'Livraison',
                    'path' => '/admin/delivery',
                    'section' => 'Delivery',
                    'description' => 'Transporteurs, comptes et expéditions.',
                    'icon' => 'truck',
                    'access' => 'admin',
                ],
                [
                    'slug' => 'super-admin',
                    'title' => 'Super Admin',
                    'path' => '/admin/super-admin',
                    'section' => 'Admin',
                    'description' => 'Pilotage plateforme et configuration globale.',
                    'icon' => 'security',
                    'access' => 'admin',
                ],
                [
                    'slug' => 'modules',
                    'title' => 'Modules plateforme',
                    'path' => '/admin/modules',
                    'section' => 'Admin',
                    'description' => 'Activation globale et configuration des modules par boutique.',
                    'icon' => 'security',
                    'access' => 'admin',
                ],
                [
                    'slug' => 'notifications',
                    'title' => 'Notifications',
                    'path' => '/admin/notifications',
                    'section' => 'Admin',
                    'description' => 'Consultation des notifications de la plateforme.',
                    'icon' => 'users',
                    'access' => 'admin',
                ],
                [
                    'slug' => 'themes',
                    'title' => 'Thèmes plateforme',
                    'path' => '/admin/themes',
                    'section' => 'Admin',
                    'description' => 'Activation et thème par défaut du storefront.',
                    'icon' => 'theme',
                    'access' => 'admin',
                ],
                [
                    'slug' => 'design-system',
                    'title' => 'Design System',
                    'path' => '/admin/design-system',
                    'section' => 'System',
                    'description' => 'Tokens, couleurs, composants et règles visuelles du back-office.',
                    'icon' => 'theme',
                    'access' => 'admin',
                ],
            ],
        );
    }
}
